import { Figtree } from "next/font/google";
import "./globals.css";

const figtreeFont = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtreeFont.variable}`}>{children}</body>
    </html>
  );
}
